### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by laggingreflex** [cezary/resolve-redirect#1]
Firstly, nice little lib, exactly what I was looking for. 👍 

But I'm getting this error. : regeneratorRuntime is not defined

This error likely occurs when the project is not using "babel-polyfill" which is what provides the `regeneratorRuntime`. I'm assuming you use babel-polyfill in most your projects so this must've gone by unnoticed. But it's causing issue for me.

Also it seems you're only using "async/await" for only 1 call. 

Would you accept a PR to remove babel-dependency altogether? This could well be done with just promises. Without it it could truly be  0 dependency lib.

**Comment by cezary** [comment]
Definitely. Merged your PRs and published the updated lib to npm, thanks for the help!
